spring.datasource.url=mysql://root:jNyxEojfglSCtubiRrimjwkJQaxfJHgZ@interchange.proxy.rlwy.net:29447/railway
spring.datasource.username=root
spring.datasource.password=jNyxEojfglSCtubiRrimjwkJQaxfJHgZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
