spring.application.name=GymBro
#server.port=${PORT:8080}
# DataSource configuration
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=jNyxEojfglSCtubiRrimjwkJQaxfJHgZ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
